INSERT INTO `t_country` VALUES (1, 'Afghanistan', '阿富汗', 'AF', 93);
INSERT INTO `t_country` VALUES (2, 'Albania', '阿尔巴尼亚', 'AL', 355);
INSERT INTO `t_country` VALUES (3, 'Algeria', '阿尔及利亚', 'DZ', 213);
INSERT INTO `t_country` VALUES (4, 'American Samoa', '美属萨摩亚', 'AS', 1684);
INSERT INTO `t_country` VALUES (5, 'Andorra', '安道尔', 'AD', 376);
INSERT INTO `t_country` VALUES (6, 'Angola', '安哥拉', 'AO', 244);
INSERT INTO `t_country` VALUES (7, 'Anguilla', '安圭拉', 'AI', 1264);
INSERT INTO `t_country` VALUES (8, 'Antigua and Barbuda', '安提瓜和巴布达', 'AG', 1268);
INSERT INTO `t_country` VALUES (9, 'Argentina', '阿根廷', 'AR', 54);
INSERT INTO `t_country` VALUES (10, 'Armenia', '亚美尼亚', 'AM', 374);
INSERT INTO `t_country` VALUES (11, 'Aruba', '阿鲁巴', 'AW', 297);
INSERT INTO `t_country` VALUES (12, 'Australia', '澳大利亚', 'AU', 61);
INSERT INTO `t_country` VALUES (13, 'Austria', '奥地利', 'AT', 43);
INSERT INTO `t_country` VALUES (14, 'Azerbaijan', '阿塞拜疆', 'AZ', 994);
INSERT INTO `t_country` VALUES (15, 'Bahamas', '巴哈马', 'BS', 1242);
INSERT INTO `t_country` VALUES (16, 'Bahrain', '巴林', 'BH', 973);
INSERT INTO `t_country` VALUES (17, 'Bangladesh', '孟加拉国', 'BD', 880);
INSERT INTO `t_country` VALUES (18, 'Barbados', '巴巴多斯', 'BB', 1246);
INSERT INTO `t_country` VALUES (19, 'Belarus', '白俄罗斯', 'BY', 375);
INSERT INTO `t_country` VALUES (20, 'Belgium', '比利时', 'BE', 32);
INSERT INTO `t_country` VALUES (21, 'Belize', '伯利兹', 'BZ', 501);
INSERT INTO `t_country` VALUES (22, 'Benin', '贝宁', 'BJ', 229);
INSERT INTO `t_country` VALUES (23, 'Bermuda', '百慕大群岛', 'BM', 1441);
INSERT INTO `t_country` VALUES (24, 'Bhutan', '不丹', 'BT', 975);
INSERT INTO `t_country` VALUES (25, 'Bolivia', '玻利维亚', 'BO', 591);
INSERT INTO `t_country` VALUES (26, 'Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那', 'BA', 387);
INSERT INTO `t_country` VALUES (27, 'Botswana', '博茨瓦纳', 'BW', 267);
INSERT INTO `t_country` VALUES (28, 'Brazil', '巴西', 'BR', 55);
INSERT INTO `t_country` VALUES (29, 'Brunei', '文莱', 'BN', 673);
INSERT INTO `t_country` VALUES (30, 'Bulgaria', '保加利亚', 'BG', 359);
INSERT INTO `t_country` VALUES (31, 'Burkina Faso', '布基纳法索', 'BF', 226);
INSERT INTO `t_country` VALUES (32, 'Burundi', '布隆迪', 'BI', 257);
INSERT INTO `t_country` VALUES (33, 'Cambodia', '柬埔寨', 'KH', 855);
INSERT INTO `t_country` VALUES (34, 'Cameroon', '喀麦隆', 'CM', 237);
INSERT INTO `t_country` VALUES (35, 'Canada', '加拿大', 'CA', 1);
INSERT INTO `t_country` VALUES (36, 'Cape Verde', '开普', 'CV', 238);
INSERT INTO `t_country` VALUES (37, 'Cayman Islands', '开曼群岛', 'KY', 1345);
INSERT INTO `t_country` VALUES (38, 'Central African Republic', '中非共和国', 'CF', 236);
INSERT INTO `t_country` VALUES (39, 'Chad', '乍得', 'TD', 235);
INSERT INTO `t_country` VALUES (40, 'China', '中国', 'CN', 86);
INSERT INTO `t_country` VALUES (41, 'Chile', '智利', 'CL', 56);
INSERT INTO `t_country` VALUES (42, 'Colombia', '哥伦比亚', 'CO', 57);
INSERT INTO `t_country` VALUES (43, 'Comoros', '科摩罗', 'KM', 269);
INSERT INTO `t_country` VALUES (44, 'Cook Islands', '库克群岛', 'CK', 682);
INSERT INTO `t_country` VALUES (45, 'Costa Rica', '哥斯达黎加', 'CR', 506);
INSERT INTO `t_country` VALUES (46, 'Croatia', '克罗地亚', 'HR', 385);
INSERT INTO `t_country` VALUES (47, 'Cuba', '古巴', 'CU', 53);
INSERT INTO `t_country` VALUES (48, 'Curacao', '库拉索', 'CW', 599);
INSERT INTO `t_country` VALUES (49, 'Cyprus', '塞浦路斯', 'CY', 357);
INSERT INTO `t_country` VALUES (50, 'Czech', '捷克', 'CZ', 420);
INSERT INTO `t_country` VALUES (51, 'Democratic Republic of the Congo', '刚果民主共和国', 'CD', 243);
INSERT INTO `t_country` VALUES (52, 'Denmark', '丹麦', 'DK', 45);
INSERT INTO `t_country` VALUES (53, 'Djibouti', '吉布提', 'DJ', 253);
INSERT INTO `t_country` VALUES (54, 'Dominica', '多米尼加', 'DM', 1767);
INSERT INTO `t_country` VALUES (55, 'Dominican Republic', '多米尼加共和国', 'DO', 1809);
INSERT INTO `t_country` VALUES (56, 'Ecuador', '厄瓜多尔', 'EC', 593);
INSERT INTO `t_country` VALUES (57, 'Egypt', '埃及', 'EG', 20);
INSERT INTO `t_country` VALUES (58, 'El Salvador', '萨尔瓦多', 'SV', 503);
INSERT INTO `t_country` VALUES (59, 'Equatorial Guinea', '赤道几内亚', 'GQ', 240);
INSERT INTO `t_country` VALUES (60, 'Eritrea', '厄立特里亚', 'ER', 291);
INSERT INTO `t_country` VALUES (61, 'Estonia', '爱沙尼亚', 'EE', 372);
INSERT INTO `t_country` VALUES (62, 'Ethiopia', '埃塞俄比亚', 'ET', 251);
INSERT INTO `t_country` VALUES (63, 'Faroe Islands', '法罗群岛', 'FO', 298);
INSERT INTO `t_country` VALUES (64, 'Fiji', '斐济', 'FJ', 679);
INSERT INTO `t_country` VALUES (65, 'Finland', '芬兰', 'FI', 358);
INSERT INTO `t_country` VALUES (66, 'France', '法国', 'FR', 33);
INSERT INTO `t_country` VALUES (67, 'French Guiana', '法属圭亚那', 'GF', 594);
INSERT INTO `t_country` VALUES (68, 'French Polynesia', '法属波利尼西亚', 'PF', 689);
INSERT INTO `t_country` VALUES (69, 'Gabon', '加蓬', 'GA', 241);
INSERT INTO `t_country` VALUES (70, 'Gambia', '冈比亚', 'GM', 220);
INSERT INTO `t_country` VALUES (71, 'Georgia', '格鲁吉亚', 'GE', 995);
INSERT INTO `t_country` VALUES (72, 'Germany', '德国', 'DE', 49);
INSERT INTO `t_country` VALUES (73, 'Ghana', '加纳', 'GH', 233);
INSERT INTO `t_country` VALUES (74, 'Gibraltar', '直布罗陀', 'GI', 350);
INSERT INTO `t_country` VALUES (75, 'Greece', '希腊', 'GR', 30);
INSERT INTO `t_country` VALUES (76, 'Greenland', '格陵兰岛', 'GL', 299);
INSERT INTO `t_country` VALUES (77, 'Grenada', '格林纳达', 'GD', 1473);
INSERT INTO `t_country` VALUES (78, 'Guadeloupe', '瓜德罗普岛', 'GP', 590);
INSERT INTO `t_country` VALUES (79, 'Guam', '关岛', 'GU', 1671);
INSERT INTO `t_country` VALUES (80, 'Guatemala', '瓜地马拉', 'GT', 502);
INSERT INTO `t_country` VALUES (81, 'Guinea', '几内亚', 'GN', 224);
INSERT INTO `t_country` VALUES (82, 'Guinea-Bissau', '几内亚比绍共和国', 'GW', 245);
INSERT INTO `t_country` VALUES (83, 'Guyana', '圭亚那', 'GY', 592);
INSERT INTO `t_country` VALUES (84, 'Haiti', '海地', 'HT', 509);
INSERT INTO `t_country` VALUES (85, 'Honduras', '洪都拉斯', 'HN', 504);
INSERT INTO `t_country` VALUES (86, 'Hong Kong', '中国香港', 'HK', 852);
INSERT INTO `t_country` VALUES (87, 'Hungary', '匈牙利', 'HU', 36);
INSERT INTO `t_country` VALUES (88, 'Iceland', '冰岛', 'IS', 354);
INSERT INTO `t_country` VALUES (89, 'India', '印度', 'IN', 91);
INSERT INTO `t_country` VALUES (90, 'Indonesia', '印度尼西亚', 'ID', 62);
INSERT INTO `t_country` VALUES (91, 'Iran', '伊朗', 'IR', 98);
INSERT INTO `t_country` VALUES (92, 'Iraq', '伊拉克', 'IQ', 964);
INSERT INTO `t_country` VALUES (93, 'Ireland', '爱尔兰', 'IE', 353);
INSERT INTO `t_country` VALUES (94, 'Israel', '以色列', 'IL', 972);
INSERT INTO `t_country` VALUES (95, 'Italy', '意大利', 'IT', 39);
INSERT INTO `t_country` VALUES (96, 'Ivory Coast', '象牙海岸', 'CI', 225);
INSERT INTO `t_country` VALUES (97, 'Jamaica', '牙买加', 'JM', 1876);
INSERT INTO `t_country` VALUES (98, 'Japan', '日本', 'JP', 81);
INSERT INTO `t_country` VALUES (99, 'Jordan', '约旦', 'JO', 962);
INSERT INTO `t_country` VALUES (100, 'Kazakhstan', '哈萨克斯坦', 'KZ', 7);
INSERT INTO `t_country` VALUES (101, 'Kenya', '肯尼亚', 'KE', 254);
INSERT INTO `t_country` VALUES (102, 'Kiribati', '基里巴斯', 'KI', 686);
INSERT INTO `t_country` VALUES (103, 'Kuwait', '科威特', 'KW', 965);
INSERT INTO `t_country` VALUES (104, 'Kyrgyzstan', '吉尔吉斯斯坦', 'KG', 996);
INSERT INTO `t_country` VALUES (105, 'Laos', '老挝', 'LA', 856);
INSERT INTO `t_country` VALUES (106, 'Latvia', '拉脱维亚', 'LV', 371);
INSERT INTO `t_country` VALUES (107, 'Lebanon', '黎巴嫩', 'LB', 961);
INSERT INTO `t_country` VALUES (108, 'Lesotho', '莱索托', 'LS', 266);
INSERT INTO `t_country` VALUES (109, 'Liberia', '利比里亚', 'LR', 231);
INSERT INTO `t_country` VALUES (110, 'Libya', '利比亚', 'LY', 218);
INSERT INTO `t_country` VALUES (111, 'Liechtenstein', '列支敦士登', 'LI', 423);
INSERT INTO `t_country` VALUES (112, 'Lithuania', '立陶宛', 'LT', 370);
INSERT INTO `t_country` VALUES (113, 'Luxembourg', '卢森堡', 'LU', 352);
INSERT INTO `t_country` VALUES (114, 'Macau', '中国澳门', 'MO', 853);
INSERT INTO `t_country` VALUES (115, 'Macedonia', '马其顿', 'MK', 389);
INSERT INTO `t_country` VALUES (116, 'Madagascar', '马达加斯加', 'MG', 261);
INSERT INTO `t_country` VALUES (117, 'Malawi', '马拉维', 'MW', 265);
INSERT INTO `t_country` VALUES (118, 'Malaysia', '马来西亚', 'MY', 60);
INSERT INTO `t_country` VALUES (119, 'Maldives', '马尔代夫', 'MV', 960);
INSERT INTO `t_country` VALUES (120, 'Mali', '马里', 'ML', 223);
INSERT INTO `t_country` VALUES (121, 'Malta', '马耳他', 'MT', 356);
INSERT INTO `t_country` VALUES (122, 'Martinique', '马提尼克', 'MQ', 596);
INSERT INTO `t_country` VALUES (123, 'Mauritania', '毛里塔尼亚', 'MR', 222);
INSERT INTO `t_country` VALUES (124, 'Mauritius', '毛里求斯', 'MU', 230);
INSERT INTO `t_country` VALUES (125, 'Mayotte', '马约特', 'YT', 269);
INSERT INTO `t_country` VALUES (126, 'Mexico', '墨西哥', 'MX', 52);
INSERT INTO `t_country` VALUES (127, 'Moldova', '摩尔多瓦', 'MD', 373);
INSERT INTO `t_country` VALUES (128, 'Monaco', '摩纳哥', 'MC', 377);
INSERT INTO `t_country` VALUES (129, 'Mongolia', '蒙古', 'MN', 976);
INSERT INTO `t_country` VALUES (130, 'Montenegro', '黑山', 'ME', 382);
INSERT INTO `t_country` VALUES (131, 'Montserrat', '蒙特塞拉特岛', 'MS', 1664);
INSERT INTO `t_country` VALUES (132, 'Morocco', '摩洛哥', 'MA', 212);
INSERT INTO `t_country` VALUES (133, 'Mozambique', '莫桑比克', 'MZ', 258);
INSERT INTO `t_country` VALUES (134, 'Myanmar', '缅甸', 'MM', 95);
INSERT INTO `t_country` VALUES (135, 'Namibia', '纳米比亚', 'NA', 264);
INSERT INTO `t_country` VALUES (136, 'Nepal', '尼泊尔', 'NP', 977);
INSERT INTO `t_country` VALUES (137, 'Netherlands', '荷兰', 'NL', 31);
INSERT INTO `t_country` VALUES (138, 'New Caledonia', '新喀里多尼亚', 'NC', 687);
INSERT INTO `t_country` VALUES (139, 'New Zealand', '新西兰', 'NZ', 64);
INSERT INTO `t_country` VALUES (140, 'Nicaragua', '尼加拉瓜', 'NI', 505);
INSERT INTO `t_country` VALUES (141, 'Niger', '尼日尔', 'NE', 227);
INSERT INTO `t_country` VALUES (142, 'Nigeria', '尼日利亚', 'NG', 234);
INSERT INTO `t_country` VALUES (143, 'Norway', '挪威', 'NO', 47);
INSERT INTO `t_country` VALUES (144, 'Oman', '阿曼', 'OM', 968);
INSERT INTO `t_country` VALUES (145, 'Pakistan', '巴基斯坦', 'PK', 92);
INSERT INTO `t_country` VALUES (146, 'Palau', '帕劳', 'PW', 680);
INSERT INTO `t_country` VALUES (147, 'Palestine', '巴勒斯坦', 'BL', 970);
INSERT INTO `t_country` VALUES (148, 'Panama', '巴拿马', 'PA', 507);
INSERT INTO `t_country` VALUES (149, 'Papua New Guinea', '巴布亚新几内亚', 'PG', 675);
INSERT INTO `t_country` VALUES (150, 'Paraguay', '巴拉圭', 'PY', 595);
INSERT INTO `t_country` VALUES (151, 'Peru', '秘鲁', 'PE', 51);
INSERT INTO `t_country` VALUES (152, 'Philippines', '菲律宾', 'PH', 63);
INSERT INTO `t_country` VALUES (153, 'Poland', '波兰', 'PL', 48);
INSERT INTO `t_country` VALUES (154, 'Portugal', '葡萄牙', 'PT', 351);
INSERT INTO `t_country` VALUES (155, 'Puerto Rico', '波多黎各', 'PR', 1787);
INSERT INTO `t_country` VALUES (156, 'Qatar', '卡塔尔', 'QA', 974);
INSERT INTO `t_country` VALUES (157, 'Republic Of The Congo', '刚果共和国', 'CG', 242);
INSERT INTO `t_country` VALUES (158, 'Réunion Island', '留尼汪', 'RE', 262);
INSERT INTO `t_country` VALUES (159, 'Romania', '罗马尼亚', 'RO', 40);
INSERT INTO `t_country` VALUES (160, 'Russia', '俄罗斯', 'RU', 7);
INSERT INTO `t_country` VALUES (161, 'Rwanda', '卢旺达', 'RW', 250);
INSERT INTO `t_country` VALUES (162, 'Saint Kitts and Nevis', '圣基茨和尼维斯', 'KN', 1869);
INSERT INTO `t_country` VALUES (163, 'Saint Lucia', '圣露西亚', 'LC', 1758);
INSERT INTO `t_country` VALUES (164, 'Saint Pierre and Miquelon', '圣彼埃尔和密克隆岛', 'PM', 508);
INSERT INTO `t_country` VALUES (165, 'Saint Vincent and The Grenadines', '圣文森特和格林纳丁斯', 'VC', 1784);
INSERT INTO `t_country` VALUES (166, 'Samoa', '萨摩亚', 'WS', 685);
INSERT INTO `t_country` VALUES (167, 'San Marino', '圣马力诺', 'SM', 378);
INSERT INTO `t_country` VALUES (168, 'Sao Tome and Principe', '圣多美和普林西比', 'ST', 239);
INSERT INTO `t_country` VALUES (169, 'Saudi Arabia', '沙特阿拉伯', 'SA', 966);
INSERT INTO `t_country` VALUES (170, 'Senegal', '塞内加尔', 'SN', 221);
INSERT INTO `t_country` VALUES (171, 'Serbia', '塞尔维亚', 'RS', 381);
INSERT INTO `t_country` VALUES (172, 'Seychelles', '塞舌尔', 'SC', 248);
INSERT INTO `t_country` VALUES (173, 'Sierra Leone', '塞拉利昂', 'SL', 232);
INSERT INTO `t_country` VALUES (174, 'Singapore', '新加坡', 'SG', 65);
INSERT INTO `t_country` VALUES (175, 'Saint Maarten (Dutch Part)', '圣马丁岛（荷兰部分）', 'SX', 1721);
INSERT INTO `t_country` VALUES (176, 'Slovakia', '斯洛伐克', 'SK', 421);
INSERT INTO `t_country` VALUES (177, 'Slovenia', '斯洛文尼亚', 'SI', 386);
INSERT INTO `t_country` VALUES (178, 'Solomon Islands', '所罗门群岛', 'SB', 677);
INSERT INTO `t_country` VALUES (179, 'Somalia', '索马里', 'SO', 252);
INSERT INTO `t_country` VALUES (180, 'South Africa', '南非', 'ZA', 27);
INSERT INTO `t_country` VALUES (181, 'South Korea', '韩国', 'KR', 82);
INSERT INTO `t_country` VALUES (182, 'Spain', '西班牙', 'ES', 34);
INSERT INTO `t_country` VALUES (183, 'Sri Lanka', '斯里兰卡', 'LK', 94);
INSERT INTO `t_country` VALUES (184, 'Sudan', '苏丹', 'SD', 249);
INSERT INTO `t_country` VALUES (185, 'Suriname', '苏里南', 'SR', 597);
INSERT INTO `t_country` VALUES (186, 'Swaziland', '斯威士兰', 'SZ', 268);
INSERT INTO `t_country` VALUES (187, 'Sweden', '瑞典', 'SE', 46);
INSERT INTO `t_country` VALUES (188, 'Switzerland', '瑞士', 'CH', 41);
INSERT INTO `t_country` VALUES (189, 'Syria', '叙利亚', 'SY', 963);
INSERT INTO `t_country` VALUES (190, 'Taiwan', '中国台湾', 'TW', 886);
INSERT INTO `t_country` VALUES (191, 'Tajikistan', '塔吉克斯坦', 'TJ', 992);
INSERT INTO `t_country` VALUES (192, 'Tanzania', '坦桑尼亚', 'TZ', 255);
INSERT INTO `t_country` VALUES (193, 'Thailand', '泰国', 'TH', 66);
INSERT INTO `t_country` VALUES (194, 'Timor-Leste', '东帝汶', 'TL', 670);
INSERT INTO `t_country` VALUES (195, 'Togo', '多哥', 'TG', 228);
INSERT INTO `t_country` VALUES (196, 'Tonga', '汤加', 'TO', 676);
INSERT INTO `t_country` VALUES (197, 'Trinidad and Tobago', '特立尼达和多巴哥', 'TT', 1868);
INSERT INTO `t_country` VALUES (198, 'Tunisia', '突尼斯', 'TN', 216);
INSERT INTO `t_country` VALUES (199, 'Turkey', '土耳其', 'TR', 90);
INSERT INTO `t_country` VALUES (200, 'Turkmenistan', '土库曼斯坦', 'TM', 993);
INSERT INTO `t_country` VALUES (201, 'Turks and Caicos Islands', '特克斯和凯科斯群岛', 'TC', 1649);
INSERT INTO `t_country` VALUES (202, 'Uganda', '乌干达', 'UG', 256);
INSERT INTO `t_country` VALUES (203, 'Ukraine', '乌克兰', 'UA', 380);
INSERT INTO `t_country` VALUES (204, 'United Arab Emirates', '阿拉伯联合酋长国', 'AE', 971);
INSERT INTO `t_country` VALUES (205, 'United Kingdom', '英国', 'GB', 44);
INSERT INTO `t_country` VALUES (206, 'United States', '美国', 'US', 1);
INSERT INTO `t_country` VALUES (207, 'Uruguay', '乌拉圭', 'UY', 598);
INSERT INTO `t_country` VALUES (208, 'Uzbekistan', '乌兹别克斯坦', 'UZ', 998);
INSERT INTO `t_country` VALUES (209, 'Vanuatu', '瓦努阿图', 'VU', 678);
INSERT INTO `t_country` VALUES (210, 'Venezuela', '委内瑞拉', 'VE', 58);
INSERT INTO `t_country` VALUES (211, 'Vietnam', '越南', 'VN', 84);
INSERT INTO `t_country` VALUES (212, 'Virgin Islands, British', '英属处女群岛', 'VG', 1340);
INSERT INTO `t_country` VALUES (213, 'Virgin Islands, US', '美属维尔京群岛', 'VI', 1284);
INSERT INTO `t_country` VALUES (214, 'Yemen', '也门', 'YE', 967);
INSERT INTO `t_country` VALUES (215, 'Zambia', '赞比亚', 'ZM', 260);
INSERT INTO `t_country` VALUES (216, 'Zimbabwe', '津巴布韦', 'ZW', 263);