CREATE TABLE `t_company_recruit` (
	`id` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '招聘ID',
	`company_id` BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '公司ID',
	`time` DATE NOT NULL,
	`event` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='公司招聘时间线'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;