-- 公司薪资待遇表
CREATE TABLE `t_company_salary` (
	`id` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '薪资待遇ID',
	`company_id` BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '公司ID',
	`category_id` INT(11) UNSIGNED ZEROFILL NOT NULL COMMENT '职位ID',
	`percent` INT(11) UNSIGNED ZEROFILL NOT NULL COMMENT '百分比',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='公司薪资待遇'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

ALTER TABLE `t_company_salary`
	CHANGE COLUMN `category_id` `job_id` INT(11) UNSIGNED ZEROFILL NOT NULL COMMENT '岗位ID' AFTER `company_id`,
	ADD COLUMN `salary_id` INT(11) UNSIGNED NOT NULL COMMENT '薪资范围ID' AFTER `job_id`;
ALTER TABLE `t_company_salary`
	CHANGE COLUMN `job_id` `job_id` BIGINT UNSIGNED ZEROFILL NOT NULL DEFAULT 0 COMMENT '岗位ID' AFTER `company_id`;

ALTER TABLE db_worldelite.t_company_salary MODIFY COLUMN percent FLOAT NOT NULL COMMENT '百分比';