CREATE TABLE `t_company_department` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '部门ID',
	`parent_id` INT(11) NOT NULL DEFAULT '0' COMMENT '父部门ID',
	`company_id` BIGINT(20) NOT NULL COMMENT '企业ID',
	`name` VARCHAR(255) NULL DEFAULT '' COMMENT '部门名' COLLATE 'utf8mb4_general_ci',
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='公司部门'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;