CREATE TABLE `t_company_environment` (
	`id` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '工作环境ID',
	`company_id` BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '公司ID',
	`image_name` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '图片名称' COLLATE 'utf8mb4_general_ci',
	`image_url` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '图片路径' COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '环境名' COLLATE 'utf8mb4_general_ci',
	`position` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='公司工作环境'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
