CREATE TABLE `t_company_honor` (
	`id` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT '荣誉ID',
	`company_id` BIGINT(20) UNSIGNED ZEROFILL NOT NULL COMMENT '公司ID',
	`year` DATE NOT NULL COMMENT '年份',
	`honor` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '公司荣誉' COLLATE 'utf8mb4_general_ci',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='公司荣誉'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;