package com.worldelite.job.mapper;

import com.worldelite.job.entity.AdditionTag;

public interface AdditionTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    int insert(AdditionTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    int insertSelective(AdditionTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    AdditionTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdditionTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_addition_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdditionTag record);
}