package com.worldelite.job.mapper;

import com.worldelite.job.entity.ChannelUser;

import java.util.List;

public interface ChannelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    int insert(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    int insertSelective(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    ChannelUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChannelUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChannelUser record);

    List<ChannelUser> selectAndList(ChannelUser channelUser);
}