package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyPost;

import java.util.List;

public interface CompanyPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int insert(CompanyPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int insertSelective(CompanyPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    CompanyPost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyPost record);

    /**
     * 查询完整数据
     * @param companyPost
     * @return
     */
    List<CompanyPost> selectAndList(CompanyPost companyPost);

    /**
     * 查询不带content字段的数据
     * @param companyPost
     * @return
     */
    List<CompanyPost> selectAndListSimple(CompanyPost companyPost);
}