package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyWiki;

import java.util.List;

public interface CompanyWikiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int insert(CompanyWiki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int insertSelective(CompanyWiki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    CompanyWiki selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyWiki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyWiki record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_wiki
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyWiki record);

    List<CompanyWiki> selectAndList(CompanyWiki options);

    CompanyWiki selectByCompanyId(Long companyId);
}