package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyForbidden;

import java.util.List;

public interface CompanyForbiddenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    int insert(CompanyForbidden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    int insertSelective(CompanyForbidden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    CompanyForbidden selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyForbidden record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_forbidden
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyForbidden record);

    List<CompanyForbidden> selectByUserId(Long userId);

    void deleteByUserId(Long userId);
}