package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyVerification;

public interface CompanyVerificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    int insert(CompanyVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    int insertSelective(CompanyVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    CompanyVerification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_verification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyVerification record);

    CompanyVerification selectByUserId(Long userId);
}