package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyStructure;

import java.util.List;

public interface CompanyStructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    int insert(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    int insertSelective(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    CompanyStructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_structure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyStructure record);

    List<CompanyStructure> selectAndList(CompanyStructure companyStructure);

    void deleteByCompanyId(Long companyId);

    void deleteByParentId(Integer parentId);
}