package com.worldelite.job.mapper;

import com.worldelite.job.entity.CompanyLike;

public interface CompanyLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    int insert(CompanyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    int insertSelective(CompanyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    CompanyLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyLike record);

    void deleteByOwnerId(Long ownerId);

    CompanyLike select(CompanyLike companyLike);
}