package com.worldelite.job.mapper;

import com.worldelite.job.entity.ConfigModule;

import java.util.List;

public interface ConfigModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    int insert(ConfigModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    int insertSelective(ConfigModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    ConfigModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigModule record);

    List<ConfigModule> selectAndList(ConfigModule configModule);
}