package com.worldelite.job.mapper;

import com.worldelite.job.entity.Download;

import java.util.Date;
import java.util.List;

public interface DownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    int insert(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    int insertSelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    Download selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Download record);

    Download selectByUrl(String url);

    List<Download> selectAndList(Download options);

    void deleteLessThanCreateTime(Date createTime);
}