package com.worldelite.job.mapper;

import com.worldelite.job.entity.JobIndustry;

import java.util.List;

public interface JobIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    int insert(JobIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    int insertSelective(JobIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    JobIndustry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JobIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job_industry
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JobIndustry record);

    List<JobIndustry> listAll();
}