package com.worldelite.job.mapper;

import com.worldelite.job.entity.NotificationMessage;
import org.apache.ibatis.annotations.Param;

public interface NotificationMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    int insert(NotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    int insertSelective(NotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    NotificationMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotificationMessage record);

    /**
     * 根据用户id和类型查询通知消息
     *
     * @param userId
     * @param type
     * @return
     */
    NotificationMessage selectByUserIdAndType(@Param("userId") String userId, @Param("type") String type, @Param("objectId") String objectId);
}