package com.worldelite.job.mapper;

import com.worldelite.job.entity.OrganizerCredit;

public interface OrganizerCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    int insert(OrganizerCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    int insertSelective(OrganizerCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    OrganizerCredit selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrganizerCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organizer_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrganizerCredit record);
}