package com.worldelite.job.mapper;

import com.worldelite.job.entity.PostMain;

public interface PostMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    int insert(PostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    int insertSelective(PostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    PostMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostMain record);
}