package com.worldelite.job.mapper;

import com.worldelite.job.entity.QuestionnaireAnswer;

public interface QuestionnaireAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    int insert(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    int insertSelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    QuestionnaireAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionnaireAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionnaireAnswer record);
}