package com.worldelite.job.mapper;

import com.worldelite.job.entity.QuestionnaireTemplate;

public interface QuestionnaireTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    int insert(QuestionnaireTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    int insertSelective(QuestionnaireTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    QuestionnaireTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionnaireTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_questionnaire_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionnaireTemplate record);
}