package com.worldelite.job.mapper;

import com.worldelite.job.entity.RealNameAuth;

import java.util.List;

public interface RealNameAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    int insert(RealNameAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    int insertSelective(RealNameAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    RealNameAuth selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RealNameAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_real_name_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RealNameAuth record);

    List<RealNameAuth> selectAndList(RealNameAuth options);
}