package com.worldelite.job.mapper;

import com.worldelite.job.entity.Recommend;

import java.util.List;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    Recommend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recommend record);

    List<Recommend> selectAndList(Recommend options);
}