package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumePractice;

public interface ResumePracticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int insert(ResumePractice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int insertSelective(ResumePractice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    ResumePractice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumePractice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ResumePractice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_practice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumePractice record);
}