package com.worldelite.job.mapper;

import com.worldelite.job.entity.Resume;
import com.worldelite.job.entity.ResumeOptions;
import com.worldelite.job.form.CountForm;
import com.worldelite.job.form.TimePairForm;

import java.util.List;

public interface ResumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int insert(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int insertSelective(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    Resume selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Resume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Resume record);

    List<Resume> selectAndList(Resume record);

    Integer countAll();

    List<CountForm> countPlaceGroupBy();

    List<TimePairForm>countGraduateTimeGroupBy();

    TimePairForm countAllByTime(ResumeOptions record);

    TimePairForm countOpResumeByTime(ResumeOptions record);

    TimePairForm countUserResumeByTime(ResumeOptions record);
}