package com.worldelite.job.mapper;

import com.worldelite.job.entity.Resume;
import com.worldelite.job.entity.ResumeApplicant;
import com.worldelite.job.entity.ResumeOptions;

import java.util.List;

public interface ResumeApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int insert(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int insertSelective(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    ResumeApplicant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeApplicant record);

    /**
     * 通过用户ID获取简历
     * @param userId
     * @return
     */
    List<Resume> selectByUserId(Long userId);

    /**
     * 通过条件筛选简历
     * @param options
     * @return
     */
    List<Resume> selectAndList(ResumeOptions options);
}