package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeLinks;

public interface ResumeLinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    int insert(ResumeLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    int insertSelective(ResumeLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    ResumeLinks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeLinks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_links
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeLinks record);
}