package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeMergeAttach;

import java.util.List;

public interface ResumeMergeAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    int insert(ResumeMergeAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    int insertSelective(ResumeMergeAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    ResumeMergeAttach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeMergeAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_merge_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeMergeAttach record);

    List<ResumeMergeAttach>selectAndList(ResumeMergeAttach record);
}