package com.worldelite.job.mapper;

import com.worldelite.job.entity.Resume;
import com.worldelite.job.entity.ResumeApplicant;
import com.worldelite.job.entity.ResumeOptions;
import com.worldelite.job.entity.ResumeRepository;

import java.util.List;

public interface ResumeApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int insert(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int insertSelective(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    ResumeApplicant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_applicant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeApplicant record);

    /**
     * 通过用户ID获取用户简历
     * 注意一个用户只能有一份简历
     * @param userId
     * @return
     */
    ResumeApplicant selectByUserId(Long userId);

    /**
     * 通过简历ID获取用户简历
     * 注意一个用户只能有一份简历
     * @param resumeId
     * @return
     */
    ResumeApplicant selectByResumeId(Long resumeId);
}