package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeDownload;

import java.util.List;

public interface ResumeDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    int insert(ResumeDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    int insertSelective(ResumeDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    ResumeDownload selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_download
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeDownload record);

    List<ResumeDownload> selectAndList(ResumeDownload resumeDownload);
}