package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeEdu;
import com.worldelite.job.entity.ResumeEduOptions;
import com.worldelite.job.form.CountForm;
import com.worldelite.job.form.TimePairForm;

import java.util.List;

public interface ResumeEduMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    int insert(ResumeEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    int insertSelective(ResumeEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    ResumeEdu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeEdu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_edu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeEdu record);

    List<ResumeEdu> selectAndList(ResumeEdu options);

    Integer countSchool();

    List<CountForm> countSchoolGroupBy();

    List<CountForm>countMajorGroupBy();

    TimePairForm countSchoolByTime(ResumeEduOptions records);
}