package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeExperience;

public interface ResumeExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int insert(ResumeExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int insertSelective(ResumeExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    ResumeExperience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ResumeExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_experience
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeExperience record);
}