package com.worldelite.job.mapper;

import com.worldelite.job.entity.ResumeRepository;

import java.util.List;

public interface ResumeRepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int insert(ResumeRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int insertSelective(ResumeRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    ResumeRepository selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResumeRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ResumeRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resume_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResumeRepository record);

    /**
     * 通过邮箱搜索
     * @param resumeRepository
     * @return
     */
    List<ResumeRepository> selectByEmail(ResumeRepository resumeRepository);

    /**
     * 通过条件检索简历
     * @param resumeRepository
     * @return
     */
    List<ResumeRepository> selectAndList(ResumeRepository resumeRepository);
}