package com.worldelite.job.mapper;

import com.worldelite.job.entity.Subscribe;

import java.util.List;

public interface SubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    int insert(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    int insertSelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    Subscribe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subscribe record);

    List<Subscribe> selectAndList(Subscribe subscribe);
}