package com.worldelite.job.mapper;

import com.worldelite.job.entity.UserExpectSalary;

public interface UserExpectSalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    int insert(UserExpectSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    int insertSelective(UserExpectSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    UserExpectSalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserExpectSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_expect_salary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserExpectSalary record);

    int deleteByResumeId(Long resumeId);

    UserExpectSalary selectByResumeId(Long resumeId);
}