package com.worldelite.job.mapper;

import com.worldelite.job.entity.UserApplicantComment;

import java.util.List;

public interface UserApplicantCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    int insert(UserApplicantComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    int insertSelective(UserApplicantComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    UserApplicantComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserApplicantComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_applicant_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserApplicantComment record);

    List<UserApplicantComment> selectByUserIdAndCompanyId(Long userApplicantId, Long companyId);
}