package com.worldelite.job.mapper;

import com.worldelite.job.entity.UserApplicant;
import com.worldelite.job.entity.UserCorporate;
import com.worldelite.job.entity.UserOptions;

import java.util.List;

public interface UserCorporateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    int insert(UserCorporate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    int insertSelective(UserCorporate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    UserCorporate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserCorporate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_corporate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCorporate record);

    UserCorporate selectByEmail(String email);

    List<UserCorporate> selectAndList(UserOptions options);
}