package com.worldelite.job.mapper;

import com.worldelite.job.entity.WikiModule;

import java.util.List;

public interface WikiModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    int insert(WikiModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    int insertSelective(WikiModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    WikiModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WikiModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wiki_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WikiModule record);

    List<WikiModule> selectAndList(WikiModule record);
}