package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   第三方登录
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_auth
 */
public class Auth {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   平台类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.auth_type
     *
     * @mbg.generated
     */
    private Byte authType;

    /**
     * Database Column Remarks:
     *   唯一ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.auth_id
     *
     * @mbg.generated
     */
    private String authId;

    /**
     * Database Column Remarks:
     *   openID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     * Database Column Remarks:
     *   是否绑定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.verified
     *
     * @mbg.generated
     */
    private Byte verified;

    /**
     * Database Column Remarks:
     *   过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.expire_time
     *
     * @mbg.generated
     */
    private Long expireTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.id
     *
     * @return the value of t_auth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.id
     *
     * @param id the value for t_auth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.user_id
     *
     * @return the value of t_auth.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.user_id
     *
     * @param userId the value for t_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.auth_type
     *
     * @return the value of t_auth.auth_type
     *
     * @mbg.generated
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.auth_type
     *
     * @param authType the value for t_auth.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.auth_id
     *
     * @return the value of t_auth.auth_id
     *
     * @mbg.generated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.auth_id
     *
     * @param authId the value for t_auth.auth_id
     *
     * @mbg.generated
     */
    public void setAuthId(String authId) {
        this.authId = authId == null ? null : authId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.open_id
     *
     * @return the value of t_auth.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.open_id
     *
     * @param openId the value for t_auth.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.verified
     *
     * @return the value of t_auth.verified
     *
     * @mbg.generated
     */
    public Byte getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.verified
     *
     * @param verified the value for t_auth.verified
     *
     * @mbg.generated
     */
    public void setVerified(Byte verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.expire_time
     *
     * @return the value of t_auth.expire_time
     *
     * @mbg.generated
     */
    public Long getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.expire_time
     *
     * @param expireTime the value for t_auth.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.create_time
     *
     * @return the value of t_auth.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.create_time
     *
     * @param createTime the value for t_auth.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.update_time
     *
     * @return the value of t_auth.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.update_time
     *
     * @param updateTime the value for t_auth.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}