package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   圈子帖子表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_company_post
 */
public class CompanyPost {
    /**
     * Database Column Remarks:
     *   帖子ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   发帖人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.from_id
     *
     * @mbg.generated
     */
    private Long fromId;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * Database Column Remarks:
     *   圈子ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.clique_id
     *
     * @mbg.generated
     */
    private Integer cliqueId;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     * Database Column Remarks:
     *   帖子图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.likes
     *
     * @mbg.generated
     */
    private Integer likes;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.comments
     *
     * @mbg.generated
     */
    private Integer comments;

    /**
     * Database Column Remarks:
     *   举报数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.reports
     *
     * @mbg.generated
     */
    private Integer reports;

    /**
     * Database Column Remarks:
     *   热度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.hots
     *
     * @mbg.generated
     */
    private Integer hots;

    /**
     * Database Column Remarks:
     *   是否推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.recommend
     *
     * @mbg.generated
     */
    private Byte recommend;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_post.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.id
     *
     * @return the value of t_company_post.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.id
     *
     * @param id the value for t_company_post.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.from_id
     *
     * @return the value of t_company_post.from_id
     *
     * @mbg.generated
     */
    public Long getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.from_id
     *
     * @param fromId the value for t_company_post.from_id
     *
     * @mbg.generated
     */
    public void setFromId(Long fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.company_id
     *
     * @return the value of t_company_post.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.company_id
     *
     * @param companyId the value for t_company_post.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.clique_id
     *
     * @return the value of t_company_post.clique_id
     *
     * @mbg.generated
     */
    public Integer getCliqueId() {
        return cliqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.clique_id
     *
     * @param cliqueId the value for t_company_post.clique_id
     *
     * @mbg.generated
     */
    public void setCliqueId(Integer cliqueId) {
        this.cliqueId = cliqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.title
     *
     * @return the value of t_company_post.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.title
     *
     * @param title the value for t_company_post.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.tags
     *
     * @return the value of t_company_post.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.tags
     *
     * @param tags the value for t_company_post.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.image
     *
     * @return the value of t_company_post.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.image
     *
     * @param image the value for t_company_post.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.likes
     *
     * @return the value of t_company_post.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.likes
     *
     * @param likes the value for t_company_post.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.comments
     *
     * @return the value of t_company_post.comments
     *
     * @mbg.generated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.comments
     *
     * @param comments the value for t_company_post.comments
     *
     * @mbg.generated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.reports
     *
     * @return the value of t_company_post.reports
     *
     * @mbg.generated
     */
    public Integer getReports() {
        return reports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.reports
     *
     * @param reports the value for t_company_post.reports
     *
     * @mbg.generated
     */
    public void setReports(Integer reports) {
        this.reports = reports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.hots
     *
     * @return the value of t_company_post.hots
     *
     * @mbg.generated
     */
    public Integer getHots() {
        return hots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.hots
     *
     * @param hots the value for t_company_post.hots
     *
     * @mbg.generated
     */
    public void setHots(Integer hots) {
        this.hots = hots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.recommend
     *
     * @return the value of t_company_post.recommend
     *
     * @mbg.generated
     */
    public Byte getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.recommend
     *
     * @param recommend the value for t_company_post.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Byte recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.create_time
     *
     * @return the value of t_company_post.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.create_time
     *
     * @param createTime the value for t_company_post.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.update_time
     *
     * @return the value of t_company_post.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.update_time
     *
     * @param updateTime the value for t_company_post.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_post.content
     *
     * @return the value of t_company_post.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_post.content
     *
     * @param content the value for t_company_post.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}