package com.worldelite.job.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   公司验证材料
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_company_verification
 */
public class CompanyVerification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   身份证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   身份证正面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.id_card_pic
     *
     * @mbg.generated
     */
    private String idCardPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.post
     *
     * @mbg.generated
     */
    private String post;

    /**
     * Database Column Remarks:
     *   公司营业执照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.company_license_pic
     *
     * @mbg.generated
     */
    private String companyLicensePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_verification.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.id
     *
     * @return the value of t_company_verification.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.id
     *
     * @param id the value for t_company_verification.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.user_id
     *
     * @return the value of t_company_verification.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.user_id
     *
     * @param userId the value for t_company_verification.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.id_card
     *
     * @return the value of t_company_verification.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.id_card
     *
     * @param idCard the value for t_company_verification.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.id_card_pic
     *
     * @return the value of t_company_verification.id_card_pic
     *
     * @mbg.generated
     */
    public String getIdCardPic() {
        return idCardPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.id_card_pic
     *
     * @param idCardPic the value for t_company_verification.id_card_pic
     *
     * @mbg.generated
     */
    public void setIdCardPic(String idCardPic) {
        this.idCardPic = idCardPic == null ? null : idCardPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.real_name
     *
     * @return the value of t_company_verification.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.real_name
     *
     * @param realName the value for t_company_verification.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.company
     *
     * @return the value of t_company_verification.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.company
     *
     * @param company the value for t_company_verification.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.post
     *
     * @return the value of t_company_verification.post
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.post
     *
     * @param post the value for t_company_verification.post
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.company_license_pic
     *
     * @return the value of t_company_verification.company_license_pic
     *
     * @mbg.generated
     */
    public String getCompanyLicensePic() {
        return companyLicensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.company_license_pic
     *
     * @param companyLicensePic the value for t_company_verification.company_license_pic
     *
     * @mbg.generated
     */
    public void setCompanyLicensePic(String companyLicensePic) {
        this.companyLicensePic = companyLicensePic == null ? null : companyLicensePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.status
     *
     * @return the value of t_company_verification.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.status
     *
     * @param status the value for t_company_verification.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.remark
     *
     * @return the value of t_company_verification.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.remark
     *
     * @param remark the value for t_company_verification.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.create_time
     *
     * @return the value of t_company_verification.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.create_time
     *
     * @param createTime the value for t_company_verification.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_verification.update_time
     *
     * @return the value of t_company_verification.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_verification.update_time
     *
     * @param updateTime the value for t_company_verification.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}