package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   企业评论表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_company_comment
 */
public class CompanyComment {
    /**
     * Database Column Remarks:
     *   评论ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   所属对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.owner_id
     *
     * @mbg.generated
     */
    private Long ownerId;

    /**
     * Database Column Remarks:
     *   所有所属ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.owner_ids
     *
     * @mbg.generated
     */
    private String ownerIds;

    /**
     * Database Column Remarks:
     *   评论人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.from_id
     *
     * @mbg.generated
     */
    private Long fromId;

    /**
     * Database Column Remarks:
     *   被评论人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.to_id
     *
     * @mbg.generated
     */
    private Long toId;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   评论类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.likes
     *
     * @mbg.generated
     */
    private Integer likes;

    /**
     * Database Column Remarks:
     *   举报数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.reports
     *
     * @mbg.generated
     */
    private Integer reports;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.comments
     *
     * @mbg.generated
     */
    private Integer comments;

    /**
     * Database Column Remarks:
     *   热度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.hots
     *
     * @mbg.generated
     */
    private Integer hots;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_comment.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.id
     *
     * @return the value of t_company_comment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.id
     *
     * @param id the value for t_company_comment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.owner_id
     *
     * @return the value of t_company_comment.owner_id
     *
     * @mbg.generated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.owner_id
     *
     * @param ownerId the value for t_company_comment.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.owner_ids
     *
     * @return the value of t_company_comment.owner_ids
     *
     * @mbg.generated
     */
    public String getOwnerIds() {
        return ownerIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.owner_ids
     *
     * @param ownerIds the value for t_company_comment.owner_ids
     *
     * @mbg.generated
     */
    public void setOwnerIds(String ownerIds) {
        this.ownerIds = ownerIds == null ? null : ownerIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.from_id
     *
     * @return the value of t_company_comment.from_id
     *
     * @mbg.generated
     */
    public Long getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.from_id
     *
     * @param fromId the value for t_company_comment.from_id
     *
     * @mbg.generated
     */
    public void setFromId(Long fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.to_id
     *
     * @return the value of t_company_comment.to_id
     *
     * @mbg.generated
     */
    public Long getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.to_id
     *
     * @param toId the value for t_company_comment.to_id
     *
     * @mbg.generated
     */
    public void setToId(Long toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.content
     *
     * @return the value of t_company_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.content
     *
     * @param content the value for t_company_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.type
     *
     * @return the value of t_company_comment.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.type
     *
     * @param type the value for t_company_comment.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.likes
     *
     * @return the value of t_company_comment.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.likes
     *
     * @param likes the value for t_company_comment.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.reports
     *
     * @return the value of t_company_comment.reports
     *
     * @mbg.generated
     */
    public Integer getReports() {
        return reports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.reports
     *
     * @param reports the value for t_company_comment.reports
     *
     * @mbg.generated
     */
    public void setReports(Integer reports) {
        this.reports = reports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.comments
     *
     * @return the value of t_company_comment.comments
     *
     * @mbg.generated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.comments
     *
     * @param comments the value for t_company_comment.comments
     *
     * @mbg.generated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.hots
     *
     * @return the value of t_company_comment.hots
     *
     * @mbg.generated
     */
    public Integer getHots() {
        return hots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.hots
     *
     * @param hots the value for t_company_comment.hots
     *
     * @mbg.generated
     */
    public void setHots(Integer hots) {
        this.hots = hots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.create_time
     *
     * @return the value of t_company_comment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.create_time
     *
     * @param createTime the value for t_company_comment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_comment.update_time
     *
     * @return the value of t_company_comment.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_comment.update_time
     *
     * @param updateTime the value for t_company_comment.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}