package com.worldelite.job.entity;

/**
 * Database Table Remarks:
 *   职位类型-行业对应表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_job_category_industry
 */
public class JobCategoryIndustry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_category_industry.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   职位类型ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_category_industry.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   行业领域ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_category_industry.industry_id
     *
     * @mbg.generated
     */
    private Long industryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_category_industry.id
     *
     * @return the value of t_job_category_industry.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_category_industry.id
     *
     * @param id the value for t_job_category_industry.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_category_industry.category_id
     *
     * @return the value of t_job_category_industry.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_category_industry.category_id
     *
     * @param categoryId the value for t_job_category_industry.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_category_industry.industry_id
     *
     * @return the value of t_job_category_industry.industry_id
     *
     * @mbg.generated
     */
    public Long getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_category_industry.industry_id
     *
     * @param industryId the value for t_job_category_industry.industry_id
     *
     * @mbg.generated
     */
    public void setIndustryId(Long industryId) {
        this.industryId = industryId;
    }
}