package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   消息通知表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_notification_message
 */
public class NotificationMessage {
    /**
     * Database Column Remarks:
     *   消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   消息归属用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   业务对象id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.object_id
     *
     * @mbg.generated
     */
    private String objectId;

    /**
     * Database Column Remarks:
     *   消息业务类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   消息内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.msg_content
     *
     * @mbg.generated
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification_message.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.id
     *
     * @return the value of t_notification_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.id
     *
     * @param id the value for t_notification_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.user_id
     *
     * @return the value of t_notification_message.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.user_id
     *
     * @param userId the value for t_notification_message.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.object_id
     *
     * @return the value of t_notification_message.object_id
     *
     * @mbg.generated
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.object_id
     *
     * @param objectId the value for t_notification_message.object_id
     *
     * @mbg.generated
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.type
     *
     * @return the value of t_notification_message.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.type
     *
     * @param type the value for t_notification_message.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.msg_content
     *
     * @return the value of t_notification_message.msg_content
     *
     * @mbg.generated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.msg_content
     *
     * @param msgContent the value for t_notification_message.msg_content
     *
     * @mbg.generated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.del_flag
     *
     * @return the value of t_notification_message.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.del_flag
     *
     * @param delFlag the value for t_notification_message.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.create_time
     *
     * @return the value of t_notification_message.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.create_time
     *
     * @param createTime the value for t_notification_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification_message.update_time
     *
     * @return the value of t_notification_message.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification_message.update_time
     *
     * @param updateTime the value for t_notification_message.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}