package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   岗位表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_post
 */
public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   主分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.main_id
     *
     * @mbg.generated
     */
    private Integer mainId;

    /**
     * Database Column Remarks:
     *   二级分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   岗位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.position
     *
     * @mbg.generated
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.id
     *
     * @return the value of t_post.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.id
     *
     * @param id the value for t_post.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.main_id
     *
     * @return the value of t_post.main_id
     *
     * @mbg.generated
     */
    public Integer getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.main_id
     *
     * @param mainId the value for t_post.main_id
     *
     * @mbg.generated
     */
    public void setMainId(Integer mainId) {
        this.mainId = mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.category_id
     *
     * @return the value of t_post.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.category_id
     *
     * @param categoryId the value for t_post.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.name
     *
     * @return the value of t_post.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.name
     *
     * @param name the value for t_post.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.position
     *
     * @return the value of t_post.position
     *
     * @mbg.generated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.position
     *
     * @param position the value for t_post.position
     *
     * @mbg.generated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.create_time
     *
     * @return the value of t_post.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.create_time
     *
     * @param createTime the value for t_post.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.update_time
     *
     * @return the value of t_post.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.update_time
     *
     * @param updateTime the value for t_post.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}