package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   报名问卷回答表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_questionnaire_answer
 */
public class QuestionnaireAnswer {
    /**
     * Database Column Remarks:
     *   问卷回答id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   报名表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.registration_id
     *
     * @mbg.generated
     */
    private Integer registrationId;

    /**
     * Database Column Remarks:
     *   问卷表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated
     */
    private Integer questionnaireId;

    /**
     * Database Column Remarks:
     *   回答内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.answer_content
     *
     * @mbg.generated
     */
    private String answerContent;

    /**
     * Database Column Remarks:
     *   回答选项id(如果是选择题)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.answer_options_id
     *
     * @mbg.generated
     */
    private Integer answerOptionsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_questionnaire_answer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.id
     *
     * @return the value of t_questionnaire_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.id
     *
     * @param id the value for t_questionnaire_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.registration_id
     *
     * @return the value of t_questionnaire_answer.registration_id
     *
     * @mbg.generated
     */
    public Integer getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.registration_id
     *
     * @param registrationId the value for t_questionnaire_answer.registration_id
     *
     * @mbg.generated
     */
    public void setRegistrationId(Integer registrationId) {
        this.registrationId = registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.questionnaire_id
     *
     * @return the value of t_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated
     */
    public Integer getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.questionnaire_id
     *
     * @param questionnaireId the value for t_questionnaire_answer.questionnaire_id
     *
     * @mbg.generated
     */
    public void setQuestionnaireId(Integer questionnaireId) {
        this.questionnaireId = questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.answer_content
     *
     * @return the value of t_questionnaire_answer.answer_content
     *
     * @mbg.generated
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.answer_content
     *
     * @param answerContent the value for t_questionnaire_answer.answer_content
     *
     * @mbg.generated
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent == null ? null : answerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.answer_options_id
     *
     * @return the value of t_questionnaire_answer.answer_options_id
     *
     * @mbg.generated
     */
    public Integer getAnswerOptionsId() {
        return answerOptionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.answer_options_id
     *
     * @param answerOptionsId the value for t_questionnaire_answer.answer_options_id
     *
     * @mbg.generated
     */
    public void setAnswerOptionsId(Integer answerOptionsId) {
        this.answerOptionsId = answerOptionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.del_flag
     *
     * @return the value of t_questionnaire_answer.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.del_flag
     *
     * @param delFlag the value for t_questionnaire_answer.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.create_time
     *
     * @return the value of t_questionnaire_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.create_time
     *
     * @param createTime the value for t_questionnaire_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_questionnaire_answer.update_time
     *
     * @return the value of t_questionnaire_answer.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_questionnaire_answer.update_time
     *
     * @param updateTime the value for t_questionnaire_answer.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}