package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   报名表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_registration
 */
public class Registration {
    /**
     * Database Column Remarks:
     *   报名表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   活动发布人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   活动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     * Database Column Remarks:
     *   报名表编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * Database Column Remarks:
     *   报名者姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     * Database Column Remarks:
     *   年级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * Database Column Remarks:
     *   专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.profession
     *
     * @mbg.generated
     */
    private String profession;

    /**
     * Database Column Remarks:
     *   学历
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     * Database Column Remarks:
     *   审核状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_registration.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.id
     *
     * @return the value of t_registration.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.id
     *
     * @param id the value for t_registration.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.user_id
     *
     * @return the value of t_registration.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.user_id
     *
     * @param userId the value for t_registration.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.activity_id
     *
     * @return the value of t_registration.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.activity_id
     *
     * @param activityId the value for t_registration.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.number
     *
     * @return the value of t_registration.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.number
     *
     * @param number the value for t_registration.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.name
     *
     * @return the value of t_registration.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.name
     *
     * @param name the value for t_registration.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.gender
     *
     * @return the value of t_registration.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.gender
     *
     * @param gender the value for t_registration.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.phone
     *
     * @return the value of t_registration.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.phone
     *
     * @param phone the value for t_registration.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.email
     *
     * @return the value of t_registration.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.email
     *
     * @param email the value for t_registration.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.school
     *
     * @return the value of t_registration.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.school
     *
     * @param school the value for t_registration.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.grade
     *
     * @return the value of t_registration.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.grade
     *
     * @param grade the value for t_registration.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.profession
     *
     * @return the value of t_registration.profession
     *
     * @mbg.generated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.profession
     *
     * @param profession the value for t_registration.profession
     *
     * @mbg.generated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.education
     *
     * @return the value of t_registration.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.education
     *
     * @param education the value for t_registration.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.status
     *
     * @return the value of t_registration.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.status
     *
     * @param status the value for t_registration.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.del_flag
     *
     * @return the value of t_registration.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.del_flag
     *
     * @param delFlag the value for t_registration.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.create_time
     *
     * @return the value of t_registration.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.create_time
     *
     * @param createTime the value for t_registration.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_registration.update_time
     *
     * @return the value of t_registration.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_registration.update_time
     *
     * @param updateTime the value for t_registration.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}