package com.worldelite.job.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_resume_attach
 */
public class ResumeAttach implements Serializable {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   简历id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.resume_id
     *
     * @mbg.generated
     */
    private Long resumeId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   附件简历内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume_attach.attach_content
     *
     * @mbg.generated
     */
    private String attachContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.id
     *
     * @return the value of t_resume_attach.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.id
     *
     * @param id the value for t_resume_attach.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.resume_id
     *
     * @return the value of t_resume_attach.resume_id
     *
     * @mbg.generated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.resume_id
     *
     * @param resumeId the value for t_resume_attach.resume_id
     *
     * @mbg.generated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.user_id
     *
     * @return the value of t_resume_attach.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.user_id
     *
     * @param userId the value for t_resume_attach.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.create_time
     *
     * @return the value of t_resume_attach.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.create_time
     *
     * @param createTime the value for t_resume_attach.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.update_time
     *
     * @return the value of t_resume_attach.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.update_time
     *
     * @param updateTime the value for t_resume_attach.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume_attach.attach_content
     *
     * @return the value of t_resume_attach.attach_content
     *
     * @mbg.generated
     */
    public String getAttachContent() {
        return attachContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume_attach.attach_content
     *
     * @param attachContent the value for t_resume_attach.attach_content
     *
     * @mbg.generated
     */
    public void setAttachContent(String attachContent) {
        this.attachContent = attachContent == null ? null : attachContent.trim();
    }
}