package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   订阅表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_subscribe
 */
public class Subscribe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.object_id
     *
     * @mbg.generated
     */
    private Long objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.object_type
     *
     * @mbg.generated
     */
    private Byte objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.position
     *
     * @mbg.generated
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.id
     *
     * @return the value of t_subscribe.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.id
     *
     * @param id the value for t_subscribe.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.user_id
     *
     * @return the value of t_subscribe.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.user_id
     *
     * @param userId the value for t_subscribe.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.object_id
     *
     * @return the value of t_subscribe.object_id
     *
     * @mbg.generated
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.object_id
     *
     * @param objectId the value for t_subscribe.object_id
     *
     * @mbg.generated
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.object_type
     *
     * @return the value of t_subscribe.object_type
     *
     * @mbg.generated
     */
    public Byte getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.object_type
     *
     * @param objectType the value for t_subscribe.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(Byte objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.position
     *
     * @return the value of t_subscribe.position
     *
     * @mbg.generated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.position
     *
     * @param position the value for t_subscribe.position
     *
     * @mbg.generated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.create_time
     *
     * @return the value of t_subscribe.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.create_time
     *
     * @param createTime the value for t_subscribe.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.update_time
     *
     * @return the value of t_subscribe.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.update_time
     *
     * @param updateTime the value for t_subscribe.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}