package com.worldelite.job.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   求职意向条件
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_expect_salary
 */
public class UserExpectSalary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   单位：千
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.min_value
     *
     * @mbg.generated
     */
    private Integer minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.max_value
     *
     * @mbg.generated
     */
    private Integer maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_expect_salary.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.id
     *
     * @return the value of t_user_expect_salary.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.id
     *
     * @param id the value for t_user_expect_salary.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.user_id
     *
     * @return the value of t_user_expect_salary.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.user_id
     *
     * @param userId the value for t_user_expect_salary.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.min_value
     *
     * @return the value of t_user_expect_salary.min_value
     *
     * @mbg.generated
     */
    public Integer getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.min_value
     *
     * @param minValue the value for t_user_expect_salary.min_value
     *
     * @mbg.generated
     */
    public void setMinValue(Integer minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.max_value
     *
     * @return the value of t_user_expect_salary.max_value
     *
     * @mbg.generated
     */
    public Integer getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.max_value
     *
     * @param maxValue the value for t_user_expect_salary.max_value
     *
     * @mbg.generated
     */
    public void setMaxValue(Integer maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.create_time
     *
     * @return the value of t_user_expect_salary.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.create_time
     *
     * @param createTime the value for t_user_expect_salary.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_expect_salary.update_time
     *
     * @return the value of t_user_expect_salary.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_expect_salary.update_time
     *
     * @param updateTime the value for t_user_expect_salary.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}